### ISSUE TITLE
Support spaces in dataset names

### ISSUE THREAD

**Issue by wlhlm** [ross/zfs-periodic#11]
While not explicitly [documented](https://docs.oracle.com/cd/E36784_01/html/E36835/gbcpt.html), it is possible (and supported by core ZFS and utilities) to create ZFS datasets with spaces in them (see https://github.com/openzfs/zfs/issues/1027 for a small discussion). zfs-periodic fails to support such datasets due to use of simplistic shell variable splitting using the default `IFS` which splits on spaces. [Example](https://github.com/ross/zfs-periodic/blob/9004e379db035e267da992444d4202d7d921e620/etc/periodic/zfs-snapshot#L35-L50) from the code:
```bash
datasets=$(zfs list -r -H -o name $pool)
# ...
for dataset in $datasets; do
```

I've noticed this only after 4 years of using zfs-periodic that one of my ZFS filesystems wasn't snapshotting properly. 😅 

Please consider supporting such datasets.

**Comment by ross** [comment]
PRs welcome. I don't really have a great setup atm for developing/testing zfs-periodic so it'll be a while before I'd get a chance to look at it.
