### ISSUE TITLE
Skipping datasets feature is not specific enough

### ISSUE THREAD

**Issue by edgeman16** [ross/zfs-periodic#2]
I believe the offending code to be:

```
    if [ -n "$skip" ]; then
egrep="($(echo $skip | sed "s/ /|/g"))"
            datasets=$(zfs list -r -H -o name $pool | egrep -v "$egrep")
    else
datasets=$(zfs list -r -H -o name $pool)
    fi
```

If I have datasets:
tank/t
tank/tv

and I don't want snapshots on tank/t
If I list it in the excludes in periodic.conf, tank/tv no longer receives snapshots.

**Comment by chrcoluk** [comment]
how does this feature even work it seems undocumented

wasting a ton of space snapshotting ports directories and usr/obj plus tmp folders.

**Comment by igwan** [comment]
[Here](https://github.com/ross/zfs-periodic/blob/master/etc/periodic.conf) you can see the different `*_zfs_snapshot_skip=""`.

**Comment by chrcoluk** [comment]
thanks but it isnt shown when installed from ports on FreeBSD, I guess I need to email the ports team to fix this?

I dont know if its reasonable to expect people to look it up on github, its not present in example conf files on the OS and is no man page or readme with it in place.  But I am very glad this feature exists so am glad I now know about it. :)
